[project]
drom-version = "0.1"

[project]
authors = ["Fabrice Le Fessant <fabrice.le_fessant@origin-labs.com>"]
copyright = "OCamlPro SAS & Origin Labs SAS"
edition = "4.10.0"
github-organization = "ocamlpro"
license = "LGPL2"
min-edition = "4.07.0"
name = "opam-bin"
sphinx-target = "."
synopsis = "The opam-bin tool is a simple framework to use `opam` with binary packages"
version = "1.2.0"
windows-ci = true

# keys that you could also define:
# odoc-target = "...odoc-target..."
# archive = "...archive..."
# dev-repo = "...dev-repo..."
# bug-reports = "...bug-reports..."
# doc-api = "...doc-api..."
# doc-gen = "...doc-gen..."
# homepage = "...homepage..."

[project]
description = """
opam-binary is a simple framework to use `opam` with binary packages.
"""

[project]
skip = "sphinx/_static/css/fixes.css sphinx/index.rst sphinx/conf.py docs/.nojekyll docs/index.html src/opam_bin_lib/main.ml src/opam_bin/main.ml CHANGES.md sphinx/install.rst sphinx/about.rst docs/README.txt"

# project-wide library dependencies (not for package-specific deps)
[dependencies]

# project-wide tools dependencies (not for package-specific deps)
[tools.ocamlformat]
for-test = true
[tools.odoc]
for-doc = true
[tools.ppx_expect]
for-test = true
[tools.ppx_inline_test]
for-test = true

[project]

# dirs to skip while scanning for dune files
skip-dirs = ["test2"]

# dirs to scan for share/ folders (with package names)
share-dirs = ["share"]

# build profile to use by default
# build-profile = ...

# Profile options for this project
#    [profile]
#    dev = { ocaml-flags = "-w +a-4-40-41-42-44" }
#    release = { ocaml-flags = "-w -a" }
[profile]
# ...

# project-wide fields (depends on project skeleton)
[fields]
# ...


[[package]]
dir = "src/opam_bin"
# edit 'src/opam_bin/package.toml' for package-specific options


[[package]]
dir = "src/opam_bin_lib"
# edit 'src/opam_bin_lib/package.toml' for package-specific options

